allOf:
  - type: object
    required:
      - id
      - uri
    properties:
      id:
        $ref: '../fields/PriceCategoryId.yaml'
      uri:
        $ref: '../../dataObjects/Uri.yaml'
  - $ref: 'PriceCategoryProperties.yaml'
