description: A list of price categories
content:
  application/json:
    schema:
      type: object
      properties:
        metadata:
          $ref: '../../schemas/MetaData.yaml'
        data:
          type: array
          items:
            $ref: '../../schemas/inventory/priceCategory/PriceCategory.yaml'
