description: A list of voucher offers
content:
  application/json:
    schema:
      type: object
      properties:
        metadata:
          $ref: '../../schemas/MetaData.yaml'
        data:
          type: array
          items:
            $ref: '../../schemas/inventory/VoucherOffer.yaml'
