allOf:
  - type: object
    required:
      - id
      - uri
    properties:
      id:
        $ref: 'fields/CouponId.yaml'
      uri:
        $ref: '../../dataObjects/Uri.yaml'
  - $ref: 'CouponProperties.yaml'
