allOf:
  - type: object
    required:
      - id
      - uri
    properties:
      id:
        $ref: 'fields/ExperienceHighlightId.yaml'
      uri:
        $ref: '../../../dataObjects/Uri.yaml'
  - $ref: 'ExperienceHighlightProperties.yaml'
